"""Auto-generated SFU event dataclasses. Do not edit manually."""

# Generated by _generate_sfu_events.py
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from dataclasses_json import DataClassJsonMixin
from google.protobuf.json_format import MessageToDict
from getstream.video.rtc.pb.stream.video.sfu.event import events_pb2
from vision_agents.core.events.base import BaseEvent

# Note: For enum fields typed as 'int', use the corresponding enum from:
# getstream.video.rtc.pb.stream.video.sfu.models.models_pb2
# Available enums: TrackType, ConnectionQuality, ErrorCode, PeerType, etc.


def _to_dict(message) -> dict[str, Any]:
    try:
        return MessageToDict(message, preserving_proto_field_name=True)
    except Exception:
        return {}


# ==============================================================================
# Message Type Wrappers
# These are wrappers for protobuf message types used in events
# ==============================================================================


@dataclass
class Browser(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Browser."""

    name: str | None = None
    version: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Browser:
        """Create from protobuf Browser."""
        if proto_obj is None:
            return cls()
        return cls(name=proto_obj.name, version=proto_obj.version)


@dataclass
class CallGrants(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.CallGrants."""

    can_publish_audio: bool | None = None
    can_publish_video: bool | None = None
    can_screenshare: bool | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> CallGrants:
        """Create from protobuf CallGrants."""
        if proto_obj is None:
            return cls()
        return cls(
            can_publish_audio=proto_obj.can_publish_audio,
            can_publish_video=proto_obj.can_publish_video,
            can_screenshare=proto_obj.can_screenshare,
        )


@dataclass
class CallState(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.CallState."""

    participants: list[Participant] | None = None
    started_at: Any | None = None
    participant_count: ParticipantCount | None = None
    pins: list[Pin] | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> CallState:
        """Create from protobuf CallState."""
        if proto_obj is None:
            return cls()
        return cls(
            participants=[
                Participant.from_proto(item) for item in proto_obj.participants
            ],
            started_at=proto_obj.started_at
            if proto_obj.HasField("started_at")
            else None,
            participant_count=ParticipantCount.from_proto(proto_obj.participant_count)
            if proto_obj.HasField("participant_count")
            else None,
            pins=[Pin.from_proto(item) for item in proto_obj.pins],
        )


@dataclass
class ClientDetails(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.ClientDetails."""

    sdk: Sdk | None = None
    os: OS | None = None
    browser: Browser | None = None
    device: Device | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> ClientDetails:
        """Create from protobuf ClientDetails."""
        if proto_obj is None:
            return cls()
        return cls(
            sdk=Sdk.from_proto(proto_obj.sdk) if proto_obj.HasField("sdk") else None,
            os=OS.from_proto(proto_obj.os) if proto_obj.HasField("os") else None,
            browser=Browser.from_proto(proto_obj.browser)
            if proto_obj.HasField("browser")
            else None,
            device=Device.from_proto(proto_obj.device)
            if proto_obj.HasField("device")
            else None,
        )


@dataclass
class Codec(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Codec."""

    payload_type: int | None = None
    name: str | None = None
    clock_rate: int | None = None
    encoding_parameters: str | None = None
    fmtp: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Codec:
        """Create from protobuf Codec."""
        if proto_obj is None:
            return cls()
        return cls(
            payload_type=proto_obj.payload_type,
            name=proto_obj.name,
            clock_rate=proto_obj.clock_rate,
            encoding_parameters=proto_obj.encoding_parameters,
            fmtp=proto_obj.fmtp,
        )


@dataclass
class Device(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Device."""

    name: str | None = None
    version: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Device:
        """Create from protobuf Device."""
        if proto_obj is None:
            return cls()
        return cls(name=proto_obj.name, version=proto_obj.version)


@dataclass
class Error(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Error.

    Enum fields (use values from models_pb2):
        - code: ErrorCode
    """

    code: int | None = None
    message: str | None = None
    should_retry: bool | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Error:
        """Create from protobuf Error."""
        if proto_obj is None:
            return cls()
        return cls(
            code=proto_obj.code,
            message=proto_obj.message,
            should_retry=proto_obj.should_retry,
        )


@dataclass
class ICETrickle(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.ICETrickle.

    Enum fields (use values from models_pb2):
        - peer_type: PeerType
    """

    peer_type: int | None = None
    ice_candidate: str | None = None
    session_id: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> ICETrickle:
        """Create from protobuf ICETrickle."""
        if proto_obj is None:
            return cls()
        return cls(
            peer_type=proto_obj.peer_type,
            ice_candidate=proto_obj.ice_candidate,
            session_id=proto_obj.session_id,
        )


@dataclass
class OS(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.OS."""

    name: str | None = None
    version: str | None = None
    architecture: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> OS:
        """Create from protobuf OS."""
        if proto_obj is None:
            return cls()
        return cls(
            name=proto_obj.name,
            version=proto_obj.version,
            architecture=proto_obj.architecture,
        )


@dataclass
class Participant(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Participant.

    Enum fields (use values from models_pb2):
        - published_tracks: TrackType
        - connection_quality: ConnectionQuality
    """

    user_id: str | None = None
    session_id: str | None = None
    published_tracks: list[int] | None = None
    joined_at: Any | None = None
    track_lookup_prefix: str | None = None
    connection_quality: int | None = None
    is_speaking: bool | None = None
    is_dominant_speaker: bool | None = None
    audio_level: float | None = None
    name: str | None = None
    image: str | None = None
    custom: Any | None = None
    roles: list[str] | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Participant:
        """Create from protobuf Participant."""
        if proto_obj is None:
            return cls()
        return cls(
            user_id=proto_obj.user_id,
            session_id=proto_obj.session_id,
            published_tracks=list(proto_obj.published_tracks),
            joined_at=proto_obj.joined_at if proto_obj.HasField("joined_at") else None,
            track_lookup_prefix=proto_obj.track_lookup_prefix,
            connection_quality=proto_obj.connection_quality,
            is_speaking=proto_obj.is_speaking,
            is_dominant_speaker=proto_obj.is_dominant_speaker,
            audio_level=proto_obj.audio_level,
            name=proto_obj.name,
            image=proto_obj.image,
            custom=proto_obj.custom if proto_obj.HasField("custom") else None,
            roles=list(proto_obj.roles),
        )


@dataclass
class ParticipantCount(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.ParticipantCount."""

    total: int | None = None
    anonymous: int | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> ParticipantCount:
        """Create from protobuf ParticipantCount."""
        if proto_obj is None:
            return cls()
        return cls(total=proto_obj.total, anonymous=proto_obj.anonymous)


@dataclass
class Pin(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Pin."""

    user_id: str | None = None
    session_id: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Pin:
        """Create from protobuf Pin."""
        if proto_obj is None:
            return cls()
        return cls(user_id=proto_obj.user_id, session_id=proto_obj.session_id)


@dataclass
class PublishOption(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.PublishOption.

    Enum fields (use values from models_pb2):
        - track_type: TrackType
    """

    track_type: int | None = None
    codec: Codec | None = None
    bitrate: int | None = None
    fps: int | None = None
    max_spatial_layers: int | None = None
    max_temporal_layers: int | None = None
    video_dimension: VideoDimension | None = None
    id: int | None = None
    use_single_layer: bool | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> PublishOption:
        """Create from protobuf PublishOption."""
        if proto_obj is None:
            return cls()
        return cls(
            track_type=proto_obj.track_type,
            codec=Codec.from_proto(proto_obj.codec)
            if proto_obj.HasField("codec")
            else None,
            bitrate=proto_obj.bitrate,
            fps=proto_obj.fps,
            max_spatial_layers=proto_obj.max_spatial_layers,
            max_temporal_layers=proto_obj.max_temporal_layers,
            video_dimension=VideoDimension.from_proto(proto_obj.video_dimension)
            if proto_obj.HasField("video_dimension")
            else None,
            id=proto_obj.id,
            use_single_layer=proto_obj.use_single_layer,
        )


@dataclass
class Sdk(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.Sdk.

    Enum fields (use values from models_pb2):
        - type: SdkType
    """

    type: int | None = None
    major: str | None = None
    minor: str | None = None
    patch: str | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> Sdk:
        """Create from protobuf Sdk."""
        if proto_obj is None:
            return cls()
        return cls(
            type=proto_obj.type,
            major=proto_obj.major,
            minor=proto_obj.minor,
            patch=proto_obj.patch,
        )


@dataclass
class SubscribeOption(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.SubscribeOption.

    Enum fields (use values from models_pb2):
        - track_type: TrackType
    """

    track_type: int | None = None
    codecs: list[Codec] | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> SubscribeOption:
        """Create from protobuf SubscribeOption."""
        if proto_obj is None:
            return cls()
        return cls(
            track_type=proto_obj.track_type,
            codecs=[Codec.from_proto(item) for item in proto_obj.codecs],
        )


@dataclass
class TrackInfo(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.TrackInfo.

    Enum fields (use values from models_pb2):
        - track_type: TrackType
    """

    track_id: str | None = None
    track_type: int | None = None
    layers: list[VideoLayer] | None = None
    mid: str | None = None
    dtx: bool | None = None
    stereo: bool | None = None
    red: bool | None = None
    muted: bool | None = None
    codec: Codec | None = None
    publish_option_id: int | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> TrackInfo:
        """Create from protobuf TrackInfo."""
        if proto_obj is None:
            return cls()
        return cls(
            track_id=proto_obj.track_id,
            track_type=proto_obj.track_type,
            layers=[VideoLayer.from_proto(item) for item in proto_obj.layers],
            mid=proto_obj.mid,
            dtx=proto_obj.dtx,
            stereo=proto_obj.stereo,
            red=proto_obj.red,
            muted=proto_obj.muted,
            codec=Codec.from_proto(proto_obj.codec)
            if proto_obj.HasField("codec")
            else None,
            publish_option_id=proto_obj.publish_option_id,
        )


@dataclass
class VideoDimension(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.VideoDimension."""

    width: int | None = None
    height: int | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> VideoDimension:
        """Create from protobuf VideoDimension."""
        if proto_obj is None:
            return cls()
        return cls(width=proto_obj.width, height=proto_obj.height)


@dataclass
class VideoLayer(DataClassJsonMixin):
    """Wrapper for stream.video.sfu.models.VideoLayer.

    Enum fields (use values from models_pb2):
        - quality: VideoQuality
    """

    rid: str | None = None
    video_dimension: VideoDimension | None = None
    bitrate: int | None = None
    fps: int | None = None
    quality: int | None = None

    @classmethod
    def from_proto(cls, proto_obj) -> VideoLayer:
        """Create from protobuf VideoLayer."""
        if proto_obj is None:
            return cls()
        return cls(
            rid=proto_obj.rid,
            video_dimension=VideoDimension.from_proto(proto_obj.video_dimension)
            if proto_obj.HasField("video_dimension")
            else None,
            bitrate=proto_obj.bitrate,
            fps=proto_obj.fps,
            quality=proto_obj.quality,
        )


# ==============================================================================
# Event Classes
# ==============================================================================


@dataclass
class AudioLevelEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.AudioLevel."""

    type: str = field(default="stream.video.sfu.event.AudioLevel", init=False)
    payload: events_pb2.AudioLevel | None = field(default=None, repr=False)

    @property
    def user_id(self) -> str | None:  # type: ignore[override]
        """Access user_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "user_id", None)

    @property
    def level(self) -> float | None:
        """Access level field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "level", None)

    @property
    def is_speaking(self) -> bool | None:
        """Access is_speaking field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "is_speaking", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.AudioLevel, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class AudioLevelChangedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.AudioLevelChanged."""

    type: str = field(default="stream.video.sfu.event.AudioLevelChanged", init=False)
    payload: events_pb2.AudioLevelChanged | None = field(default=None, repr=False)

    @property
    def audio_levels(self) -> list[Any] | None:
        """Access audio_levels field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "audio_levels", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.AudioLevelChanged, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class AudioSenderEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.AudioSender."""

    type: str = field(default="stream.video.sfu.event.AudioSender", init=False)
    payload: events_pb2.AudioSender | None = field(default=None, repr=False)

    @property
    def codec(self) -> Codec | None:
        """Access codec field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "codec", None)
        return Codec.from_proto(proto_val) if proto_val is not None else None

    @property
    def track_type(self) -> int | None:
        """Access track_type field from the protobuf payload. Use models_pb2.TrackType enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "track_type", None)

    @property
    def publish_option_id(self) -> int | None:
        """Access publish_option_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "publish_option_id", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.AudioSender, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class CallEndedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.CallEnded."""

    type: str = field(default="stream.video.sfu.event.CallEnded", init=False)
    payload: events_pb2.CallEnded | None = field(default=None, repr=False)

    @property
    def reason(self) -> int | None:
        """Access reason field from the protobuf payload. Use models_pb2.CallEndedReason enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reason", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.CallEnded, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class CallGrantsUpdatedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.CallGrantsUpdated."""

    type: str = field(default="stream.video.sfu.event.CallGrantsUpdated", init=False)
    payload: events_pb2.CallGrantsUpdated | None = field(default=None, repr=False)

    @property
    def current_grants(self) -> CallGrants | None:
        """Access current_grants field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "current_grants", None)
        return CallGrants.from_proto(proto_val) if proto_val is not None else None

    @property
    def message(self) -> str | None:
        """Access message field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "message", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.CallGrantsUpdated, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ChangePublishOptionsEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ChangePublishOptions."""

    type: str = field(default="stream.video.sfu.event.ChangePublishOptions", init=False)
    payload: events_pb2.ChangePublishOptions | None = field(default=None, repr=False)

    @property
    def publish_options(self) -> list[PublishOption] | None:
        """Access publish_options field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "publish_options", [])
        return (
            [PublishOption.from_proto(item) for item in proto_list]
            if proto_list
            else None
        )

    @property
    def reason(self) -> str | None:
        """Access reason field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reason", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ChangePublishOptions, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ChangePublishOptionsCompleteEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ChangePublishOptionsComplete."""

    type: str = field(
        default="stream.video.sfu.event.ChangePublishOptionsComplete", init=False
    )
    payload: events_pb2.ChangePublishOptionsComplete | None = field(
        default=None, repr=False
    )

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ChangePublishOptionsComplete, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ChangePublishQualityEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ChangePublishQuality."""

    type: str = field(default="stream.video.sfu.event.ChangePublishQuality", init=False)
    payload: events_pb2.ChangePublishQuality | None = field(default=None, repr=False)

    @property
    def audio_senders(self) -> list[Any] | None:
        """Access audio_senders field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "audio_senders", None)

    @property
    def video_senders(self) -> list[Any] | None:
        """Access video_senders field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "video_senders", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ChangePublishQuality, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ConnectionQualityChangedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ConnectionQualityChanged."""

    type: str = field(
        default="stream.video.sfu.event.ConnectionQualityChanged", init=False
    )
    payload: events_pb2.ConnectionQualityChanged | None = field(
        default=None, repr=False
    )

    @property
    def connection_quality_updates(self) -> list[Any] | None:
        """Access connection_quality_updates field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "connection_quality_updates", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ConnectionQualityChanged, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ConnectionQualityInfoEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ConnectionQualityInfo."""

    type: str = field(
        default="stream.video.sfu.event.ConnectionQualityInfo", init=False
    )
    payload: events_pb2.ConnectionQualityInfo | None = field(default=None, repr=False)

    @property
    def user_id(self) -> str | None:  # type: ignore[override]
        """Access user_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "user_id", None)

    @property
    def connection_quality(self) -> int | None:
        """Access connection_quality field from the protobuf payload. Use models_pb2.ConnectionQuality enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "connection_quality", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ConnectionQualityInfo, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class DominantSpeakerChangedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.DominantSpeakerChanged."""

    type: str = field(
        default="stream.video.sfu.event.DominantSpeakerChanged", init=False
    )
    payload: events_pb2.DominantSpeakerChanged | None = field(default=None, repr=False)

    @property
    def user_id(self) -> str | None:  # type: ignore[override]
        """Access user_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "user_id", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.DominantSpeakerChanged, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ErrorEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.Error."""

    type: str = field(default="stream.video.sfu.event.Error", init=False)
    payload: events_pb2.Error | None = field(default=None, repr=False)

    @property
    def error(self) -> Error | None:
        """Access error field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "error", None)
        return Error.from_proto(proto_val) if proto_val is not None else None

    @property
    def reconnect_strategy(self) -> int | None:
        """Access reconnect_strategy field from the protobuf payload. Use models_pb2.WebsocketReconnectStrategy enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reconnect_strategy", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.Error, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class GoAwayEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.GoAway."""

    type: str = field(default="stream.video.sfu.event.GoAway", init=False)
    payload: events_pb2.GoAway | None = field(default=None, repr=False)

    @property
    def reason(self) -> int | None:
        """Access reason field from the protobuf payload. Use models_pb2.GoAwayReason enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reason", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.GoAway, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class HealthCheckRequestEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.HealthCheckRequest."""

    type: str = field(default="stream.video.sfu.event.HealthCheckRequest", init=False)
    payload: events_pb2.HealthCheckRequest | None = field(default=None, repr=False)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.HealthCheckRequest, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class HealthCheckResponseEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.HealthCheckResponse."""

    type: str = field(default="stream.video.sfu.event.HealthCheckResponse", init=False)
    payload: events_pb2.HealthCheckResponse | None = field(default=None, repr=False)

    @property
    def participant_count(self) -> ParticipantCount | None:
        """Access participant_count field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "participant_count", None)
        return ParticipantCount.from_proto(proto_val) if proto_val is not None else None

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.HealthCheckResponse, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ICERestartEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ICERestart."""

    type: str = field(default="stream.video.sfu.event.ICERestart", init=False)
    payload: events_pb2.ICERestart | None = field(default=None, repr=False)

    @property
    def peer_type(self) -> int | None:
        """Access peer_type field from the protobuf payload. Use models_pb2.PeerType enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "peer_type", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ICERestart, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ICETrickleEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ICETrickle."""

    type: str = field(default="stream.video.sfu.event.ICETrickle", init=False)
    payload: events_pb2.ICETrickle | None = field(default=None, repr=False)

    @property
    def peer_type(self) -> int | None:
        """Access peer_type field from the protobuf payload. Use models_pb2.PeerType enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "peer_type", None)

    @property
    def ice_candidate(self) -> str | None:
        """Access ice_candidate field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "ice_candidate", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ICETrickle, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class InboundStateNotificationEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.InboundStateNotification."""

    type: str = field(
        default="stream.video.sfu.event.InboundStateNotification", init=False
    )
    payload: events_pb2.InboundStateNotification | None = field(
        default=None, repr=False
    )

    @property
    def inbound_video_states(self) -> list[Any] | None:
        """Access inbound_video_states field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "inbound_video_states", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.InboundStateNotification, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class InboundVideoStateEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.InboundVideoState."""

    type: str = field(default="stream.video.sfu.event.InboundVideoState", init=False)
    payload: events_pb2.InboundVideoState | None = field(default=None, repr=False)

    @property
    def user_id(self) -> str | None:  # type: ignore[override]
        """Access user_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "user_id", None)

    @property
    def track_type(self) -> int | None:
        """Access track_type field from the protobuf payload. Use models_pb2.TrackType enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "track_type", None)

    @property
    def paused(self) -> bool | None:
        """Access paused field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "paused", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.InboundVideoState, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class JoinRequestEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.JoinRequest."""

    type: str = field(default="stream.video.sfu.event.JoinRequest", init=False)
    payload: events_pb2.JoinRequest | None = field(default=None, repr=False)

    @property
    def token(self) -> str | None:
        """Access token field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "token", None)

    @property
    def subscriber_sdp(self) -> str | None:
        """Access subscriber_sdp field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "subscriber_sdp", None)

    @property
    def publisher_sdp(self) -> str | None:
        """Access publisher_sdp field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "publisher_sdp", None)

    @property
    def client_details(self) -> ClientDetails | None:
        """Access client_details field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "client_details", None)
        return ClientDetails.from_proto(proto_val) if proto_val is not None else None

    @property
    def migration(self) -> Any | None:
        """Access migration field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "migration", None)

    @property
    def fast_reconnect(self) -> bool | None:
        """Access fast_reconnect field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "fast_reconnect", None)

    @property
    def reconnect_details(self) -> Any | None:
        """Access reconnect_details field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reconnect_details", None)

    @property
    def preferred_publish_options(self) -> list[PublishOption] | None:
        """Access preferred_publish_options field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "preferred_publish_options", [])
        return (
            [PublishOption.from_proto(item) for item in proto_list]
            if proto_list
            else None
        )

    @property
    def preferred_subscribe_options(self) -> list[SubscribeOption] | None:
        """Access preferred_subscribe_options field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "preferred_subscribe_options", [])
        return (
            [SubscribeOption.from_proto(item) for item in proto_list]
            if proto_list
            else None
        )

    @property
    def capabilities(self) -> list[int] | None:
        """Access capabilities field from the protobuf payload. Use models_pb2.ClientCapability enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "capabilities", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.JoinRequest, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class JoinResponseEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.JoinResponse."""

    type: str = field(default="stream.video.sfu.event.JoinResponse", init=False)
    payload: events_pb2.JoinResponse | None = field(default=None, repr=False)

    @property
    def call_state(self) -> CallState | None:
        """Access call_state field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "call_state", None)
        return CallState.from_proto(proto_val) if proto_val is not None else None

    @property
    def reconnected(self) -> bool | None:
        """Access reconnected field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reconnected", None)

    @property
    def fast_reconnect_deadline_seconds(self) -> int | None:
        """Access fast_reconnect_deadline_seconds field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "fast_reconnect_deadline_seconds", None)

    @property
    def publish_options(self) -> list[PublishOption] | None:
        """Access publish_options field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "publish_options", [])
        return (
            [PublishOption.from_proto(item) for item in proto_list]
            if proto_list
            else None
        )

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.JoinResponse, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class LeaveCallRequestEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.LeaveCallRequest."""

    type: str = field(default="stream.video.sfu.event.LeaveCallRequest", init=False)
    payload: events_pb2.LeaveCallRequest | None = field(default=None, repr=False)

    @property
    def reason(self) -> str | None:
        """Access reason field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reason", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.LeaveCallRequest, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class MigrationEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.Migration."""

    type: str = field(default="stream.video.sfu.event.Migration", init=False)
    payload: events_pb2.Migration | None = field(default=None, repr=False)

    @property
    def from_sfu_id(self) -> str | None:
        """Access from_sfu_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "from_sfu_id", None)

    @property
    def announced_tracks(self) -> list[TrackInfo] | None:
        """Access announced_tracks field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "announced_tracks", [])
        return (
            [TrackInfo.from_proto(item) for item in proto_list] if proto_list else None
        )

    @property
    def subscriptions(self) -> list[Any] | None:
        """Access subscriptions field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "subscriptions", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.Migration, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ParticipantJoinedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ParticipantJoined."""

    type: str = field(default="stream.video.sfu.event.ParticipantJoined", init=False)
    payload: events_pb2.ParticipantJoined | None = field(default=None, repr=False)
    _participant: Participant | None = field(init=False, default=None, repr=False)

    @property
    def call_cid(self) -> str | None:
        """Access call_cid field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "call_cid", None)

    @property  # type: ignore[misc]
    def participant(self) -> Participant | None:  # type: ignore[override]
        """Access participant field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "participant", None)
        return Participant.from_proto(proto_val) if proto_val is not None else None

    @participant.setter  # type: ignore[misc]
    def participant(self, value: Participant | None) -> None:
        """Setter for participant to satisfy dataclass __init__."""
        # Store in _participant but don't use it (payload takes precedence)
        self._participant = value

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ParticipantJoined, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ParticipantLeftEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ParticipantLeft."""

    type: str = field(default="stream.video.sfu.event.ParticipantLeft", init=False)
    payload: events_pb2.ParticipantLeft | None = field(default=None, repr=False)
    _participant: Participant | None = field(init=False, default=None, repr=False)

    @property
    def call_cid(self) -> str | None:
        """Access call_cid field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "call_cid", None)

    @property  # type: ignore[misc]
    def participant(self) -> Participant | None:  # type: ignore[override]
        """Access participant field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "participant", None)
        return Participant.from_proto(proto_val) if proto_val is not None else None

    @participant.setter  # type: ignore[misc]
    def participant(self, value: Participant | None) -> None:
        """Setter for participant to satisfy dataclass __init__."""
        # Store in _participant but don't use it (payload takes precedence)
        self._participant = value

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ParticipantLeft, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ParticipantMigrationCompleteEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ParticipantMigrationComplete."""

    type: str = field(
        default="stream.video.sfu.event.ParticipantMigrationComplete", init=False
    )
    payload: events_pb2.ParticipantMigrationComplete | None = field(
        default=None, repr=False
    )

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ParticipantMigrationComplete, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ParticipantUpdatedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ParticipantUpdated."""

    type: str = field(default="stream.video.sfu.event.ParticipantUpdated", init=False)
    payload: events_pb2.ParticipantUpdated | None = field(default=None, repr=False)
    _participant: Participant | None = field(init=False, default=None, repr=False)

    @property
    def call_cid(self) -> str | None:
        """Access call_cid field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "call_cid", None)

    @property  # type: ignore[misc]
    def participant(self) -> Participant | None:  # type: ignore[override]
        """Access participant field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "participant", None)
        return Participant.from_proto(proto_val) if proto_val is not None else None

    @participant.setter  # type: ignore[misc]
    def participant(self, value: Participant | None) -> None:
        """Setter for participant to satisfy dataclass __init__."""
        # Store in _participant but don't use it (payload takes precedence)
        self._participant = value

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ParticipantUpdated, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class PinsChangedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.PinsChanged."""

    type: str = field(default="stream.video.sfu.event.PinsChanged", init=False)
    payload: events_pb2.PinsChanged | None = field(default=None, repr=False)

    @property
    def pins(self) -> list[Pin] | None:
        """Access pins field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "pins", [])
        return [Pin.from_proto(item) for item in proto_list] if proto_list else None

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.PinsChanged, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class PublisherAnswerEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.PublisherAnswer."""

    type: str = field(default="stream.video.sfu.event.PublisherAnswer", init=False)
    payload: events_pb2.PublisherAnswer | None = field(default=None, repr=False)

    @property
    def sdp(self) -> str | None:
        """Access sdp field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "sdp", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.PublisherAnswer, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class ReconnectDetailsEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.ReconnectDetails."""

    type: str = field(default="stream.video.sfu.event.ReconnectDetails", init=False)
    payload: events_pb2.ReconnectDetails | None = field(default=None, repr=False)

    @property
    def strategy(self) -> int | None:
        """Access strategy field from the protobuf payload. Use models_pb2.WebsocketReconnectStrategy enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "strategy", None)

    @property
    def announced_tracks(self) -> list[TrackInfo] | None:
        """Access announced_tracks field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_list = getattr(self.payload, "announced_tracks", [])
        return (
            [TrackInfo.from_proto(item) for item in proto_list] if proto_list else None
        )

    @property
    def subscriptions(self) -> list[Any] | None:
        """Access subscriptions field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "subscriptions", None)

    @property
    def reconnect_attempt(self) -> int | None:
        """Access reconnect_attempt field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reconnect_attempt", None)

    @property
    def from_sfu_id(self) -> str | None:
        """Access from_sfu_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "from_sfu_id", None)

    @property
    def previous_session_id(self) -> str | None:
        """Access previous_session_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "previous_session_id", None)

    @property
    def reason(self) -> str | None:
        """Access reason field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "reason", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.ReconnectDetails, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class SfuEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.SfuEvent."""

    type: str = field(default="stream.video.sfu.event.SfuEvent", init=False)
    payload: events_pb2.SfuEvent | None = field(default=None, repr=False)

    @property
    def subscriber_offer(self) -> Any | None:
        """Access subscriber_offer field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "subscriber_offer", None)

    @property
    def publisher_answer(self) -> Any | None:
        """Access publisher_answer field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "publisher_answer", None)

    @property
    def connection_quality_changed(self) -> Any | None:
        """Access connection_quality_changed field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "connection_quality_changed", None)

    @property
    def audio_level_changed(self) -> Any | None:
        """Access audio_level_changed field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "audio_level_changed", None)

    @property
    def ice_trickle(self) -> ICETrickle | None:
        """Access ice_trickle field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "ice_trickle", None)
        return ICETrickle.from_proto(proto_val) if proto_val is not None else None

    @property
    def change_publish_quality(self) -> Any | None:
        """Access change_publish_quality field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "change_publish_quality", None)

    @property
    def participant_joined(self) -> Any | None:
        """Access participant_joined field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "participant_joined", None)

    @property
    def participant_left(self) -> Any | None:
        """Access participant_left field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "participant_left", None)

    @property
    def dominant_speaker_changed(self) -> Any | None:
        """Access dominant_speaker_changed field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "dominant_speaker_changed", None)

    @property
    def join_response(self) -> Any | None:
        """Access join_response field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "join_response", None)

    @property
    def health_check_response(self) -> Any | None:
        """Access health_check_response field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "health_check_response", None)

    @property
    def track_published(self) -> Any | None:
        """Access track_published field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "track_published", None)

    @property
    def track_unpublished(self) -> Any | None:
        """Access track_unpublished field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "track_unpublished", None)

    @property
    def error(self) -> Any | None:
        """Access error field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "error", None)

    @property
    def call_grants_updated(self) -> Any | None:
        """Access call_grants_updated field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "call_grants_updated", None)

    @property
    def go_away(self) -> Any | None:
        """Access go_away field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "go_away", None)

    @property
    def ice_restart(self) -> Any | None:
        """Access ice_restart field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "ice_restart", None)

    @property
    def pins_updated(self) -> Any | None:
        """Access pins_updated field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "pins_updated", None)

    @property
    def call_ended(self) -> Any | None:
        """Access call_ended field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "call_ended", None)

    @property
    def participant_updated(self) -> Any | None:
        """Access participant_updated field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "participant_updated", None)

    @property
    def participant_migration_complete(self) -> Any | None:
        """Access participant_migration_complete field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "participant_migration_complete", None)

    @property
    def change_publish_options(self) -> Any | None:
        """Access change_publish_options field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "change_publish_options", None)

    @property
    def inbound_state_notification(self) -> Any | None:
        """Access inbound_state_notification field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "inbound_state_notification", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.SfuEvent, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class SfuRequestEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.SfuRequest."""

    type: str = field(default="stream.video.sfu.event.SfuRequest", init=False)
    payload: events_pb2.SfuRequest | None = field(default=None, repr=False)

    @property
    def join_request(self) -> Any | None:
        """Access join_request field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "join_request", None)

    @property
    def health_check_request(self) -> Any | None:
        """Access health_check_request field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "health_check_request", None)

    @property
    def leave_call_request(self) -> Any | None:
        """Access leave_call_request field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "leave_call_request", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.SfuRequest, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class SubscriberOfferEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.SubscriberOffer."""

    type: str = field(default="stream.video.sfu.event.SubscriberOffer", init=False)
    payload: events_pb2.SubscriberOffer | None = field(default=None, repr=False)

    @property
    def ice_restart(self) -> bool | None:
        """Access ice_restart field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "ice_restart", None)

    @property
    def sdp(self) -> str | None:
        """Access sdp field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "sdp", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.SubscriberOffer, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class TrackPublishedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.TrackPublished."""

    type: str = field(default="stream.video.sfu.event.TrackPublished", init=False)
    payload: events_pb2.TrackPublished | None = field(default=None, repr=False)
    _participant: Participant | None = field(init=False, default=None, repr=False)

    @property
    def user_id(self) -> str | None:  # type: ignore[override]
        """Access user_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "user_id", None)

    @property  # type: ignore[misc]
    def participant(self) -> Participant | None:  # type: ignore[override]
        """Access participant field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "participant", None)
        return Participant.from_proto(proto_val) if proto_val is not None else None

    @participant.setter  # type: ignore[misc]
    def participant(self, value: Participant | None) -> None:
        """Setter for participant to satisfy dataclass __init__."""
        # Store in _participant but don't use it (payload takes precedence)
        self._participant = value

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.TrackPublished, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class TrackUnpublishedEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.TrackUnpublished."""

    type: str = field(default="stream.video.sfu.event.TrackUnpublished", init=False)
    payload: events_pb2.TrackUnpublished | None = field(default=None, repr=False)
    _participant: Participant | None = field(init=False, default=None, repr=False)

    @property
    def user_id(self) -> str | None:  # type: ignore[override]
        """Access user_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "user_id", None)

    @property
    def cause(self) -> int | None:
        """Access cause field from the protobuf payload. Use models_pb2.TrackUnpublishReason enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "cause", None)

    @property  # type: ignore[misc]
    def participant(self) -> Participant | None:  # type: ignore[override]
        """Access participant field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "participant", None)
        return Participant.from_proto(proto_val) if proto_val is not None else None

    @participant.setter  # type: ignore[misc]
    def participant(self, value: Participant | None) -> None:
        """Setter for participant to satisfy dataclass __init__."""
        # Store in _participant but don't use it (payload takes precedence)
        self._participant = value

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.TrackUnpublished, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class VideoLayerSettingEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.VideoLayerSetting."""

    type: str = field(default="stream.video.sfu.event.VideoLayerSetting", init=False)
    payload: events_pb2.VideoLayerSetting | None = field(default=None, repr=False)

    @property
    def name(self) -> str | None:
        """Access name field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "name", None)

    @property
    def active(self) -> bool | None:
        """Access active field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "active", None)

    @property
    def max_bitrate(self) -> int | None:
        """Access max_bitrate field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "max_bitrate", None)

    @property
    def scale_resolution_down_by(self) -> float | None:
        """Access scale_resolution_down_by field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "scale_resolution_down_by", None)

    @property
    def codec(self) -> Codec | None:
        """Access codec field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "codec", None)
        return Codec.from_proto(proto_val) if proto_val is not None else None

    @property
    def max_framerate(self) -> int | None:
        """Access max_framerate field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "max_framerate", None)

    @property
    def scalability_mode(self) -> str | None:
        """Access scalability_mode field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "scalability_mode", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.VideoLayerSetting, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


@dataclass
class VideoSenderEvent(BaseEvent):
    """Dataclass event for video.sfu.event.events_pb2.VideoSender."""

    type: str = field(default="stream.video.sfu.event.VideoSender", init=False)
    payload: events_pb2.VideoSender | None = field(default=None, repr=False)

    @property
    def codec(self) -> Codec | None:
        """Access codec field from the protobuf payload."""
        if self.payload is None:
            return None
        proto_val = getattr(self.payload, "codec", None)
        return Codec.from_proto(proto_val) if proto_val is not None else None

    @property
    def layers(self) -> list[Any] | None:
        """Access layers field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "layers", None)

    @property
    def track_type(self) -> int | None:
        """Access track_type field from the protobuf payload. Use models_pb2.TrackType enum."""
        if self.payload is None:
            return None
        return getattr(self.payload, "track_type", None)

    @property
    def publish_option_id(self) -> int | None:
        """Access publish_option_id field from the protobuf payload."""
        if self.payload is None:
            return None
        return getattr(self.payload, "publish_option_id", None)

    @classmethod
    def from_proto(cls, proto_obj: events_pb2.VideoSender, **extra):
        """Create event instance from protobuf message."""
        return cls(payload=proto_obj, **extra)

    def as_dict(self) -> dict[str, Any]:
        """Convert protobuf payload to dictionary."""
        if self.payload is None:
            return {}
        return _to_dict(self.payload)

    def __getattr__(self, item: str):
        """Delegate attribute access to protobuf payload."""
        if self.payload is not None:
            return getattr(self.payload, item)
        raise AttributeError(
            f"'{self.__class__.__name__}' object has no attribute '{item}'"
        )


__all__ = (
    "AudioLevelEvent",
    "AudioLevelChangedEvent",
    "AudioSenderEvent",
    "CallEndedEvent",
    "CallGrantsUpdatedEvent",
    "ChangePublishOptionsEvent",
    "ChangePublishOptionsCompleteEvent",
    "ChangePublishQualityEvent",
    "ConnectionQualityChangedEvent",
    "ConnectionQualityInfoEvent",
    "DominantSpeakerChangedEvent",
    "ErrorEvent",
    "GoAwayEvent",
    "HealthCheckRequestEvent",
    "HealthCheckResponseEvent",
    "ICERestartEvent",
    "ICETrickleEvent",
    "InboundStateNotificationEvent",
    "InboundVideoStateEvent",
    "JoinRequestEvent",
    "JoinResponseEvent",
    "LeaveCallRequestEvent",
    "MigrationEvent",
    "ParticipantJoinedEvent",
    "ParticipantLeftEvent",
    "ParticipantMigrationCompleteEvent",
    "ParticipantUpdatedEvent",
    "PinsChangedEvent",
    "PublisherAnswerEvent",
    "ReconnectDetailsEvent",
    "SfuEvent",
    "SfuRequestEvent",
    "SubscriberOfferEvent",
    "TrackPublishedEvent",
    "TrackUnpublishedEvent",
    "VideoLayerSettingEvent",
    "VideoSenderEvent",
)
